# Generated by Django 2.0.3 on 2018-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='pictures')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
